### ISSUE TITLE
Crypto conflict

### ISSUE THREAD

**Issue by maksimfedin** [bigchaindb/cryptoconditions#107]
Please have a look at the issue on stackoverflow:

https://stackoverflow.com/questions/51814965/python-library-crypto-conflict

**Comment by maksimfedin** [comment]
what will be approximate timing for that issue?

**Comment by ttmc** [comment]
We probably need to resolve issue #105 first, and we have several other things going besides. Maybe we will get to this issue next week or the week after that?

**Comment by maksimfedin** [comment]
Thank you very much, would be great.

**Comment by maksimfedin** [comment]
Hi, are timing for this issue still the same? this-next week?

**Comment by codegeschrei** [comment]
Hey @maksimfedin we could reproduce the error and currently try to fix it :)

**Comment by maksimfedin** [comment]
@codegeschrei Thank you. Can you please let me know when it is fixed.

**Comment by ttmc** [comment]
I'm reopening this issue because, as noted above, there's still a problem.

**Comment by muawiakh** [comment]
@maksimfedin what version of cryptoconditions do you have?

**Comment by ttmc** [comment]
@stefanvangastel This thread is about the `cryptoconditions` package, which is used by BigchainDB but is also used by other things.

In any case, please don't use BigchainDB 1.x. Use the latest 2.x release. As I write this, that is BigchainDB 2.0.0b7 (Beta 7).
