### ISSUE TITLE
Try to shorten the description in setup.py and on github

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/cryptoconditions#5]
The `description` given in `setup.py` and on github is quite lengthy. Could we find a way to capture the essence of cryptoconditions in fewer words?

This would be useful when referring to cryptoconditions.

E.g.:

* python port from the Interledger Protocol (ILP)
* multi-algorithm, multi-level, multi-signature standard format for expressing conditions and fulfillments
* multi-signature standard for expressing conditions and fulfillments

**Comment by sbellem** [comment]
How about simply:

"Multi-signature for conditions and fulfillments."

**Comment by diminator** [comment]
going for:
- Multi-algorithm, multi-level, multi-signature format for expressing conditions and fulfillments according to the Interledger Protocol (ILP).
